---
# tasks for python

- stat: path='{{ python_python }}'
  register: python_python_file
  tags: [python, build]

- name: Remove old python repository
  apt_repository:
    repo: ppa:jonathonf/python-3.6
    state: absent

- name: Add python repository
  apt_repository:
    repo: '{{ python_repo }}'

- name: Install python apt packages
  apt:
    update_cache: yes
    name: '{{ python_packages }}'
    state: present
